#!/bin/bash

webdir="/var/www/nek.zone"
imgdir="img/art"
webpage="art/$1.html"

mogrify -path $webdir/$imgdir/$1/thumbs -thumbnail '115x115^' -gravity center -extent 115x115x $2
mv $2 $webdir/$imgdir/$1/
sed -i '/<!-- Gallery -->/a <a href="../'$imgdir'/'$1'/'$2'"><img src="../'$imgdir'/'$1'/thumbs/'$2'"></a>' $webdir/$webpage
